<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net48</TargetFramework>
        <Authors>wexels.dev</Authors>
        <Copyright>Copyright (с) Bykov Ivan Dmitrievich 2025</Copyright>
        <Configurations>Release;Debug</Configurations>
        <Platforms>x64</Platforms>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
      <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Hazbin.Core\Hazbin.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\..\..\sl_libs\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="LabApi">
        <HintPath>..\..\..\sl_libs\LabApi.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
