<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net48</TargetFramework>
        <Authors>wexels.dev</Authors>
        <Copyright>Copyright (с) Bykov Ivan Dmitrievich 2025</Copyright>
        <Configurations>Release;Debug</Configurations>
        <Platforms>x64</Platforms>
        <AssemblyVersion>0.0.0.0</AssemblyVersion>
        <FileVersion>0.0.0.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>..\..\..\sl_libs\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\..\..\sl_libs\Assembly-CSharp-Publicized.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>..\..\..\sl_libs\Assembly-CSharp-firstpass.dll</HintPath>
      </Reference>
      <Reference Include="CommandSystem.Core">
        <HintPath>..\..\..\sl_libs\CommandSystem.Core.dll</HintPath>
      </Reference>
      <Reference Include="Exiled.API">
        <HintPath>..\..\..\sl_libs\Exiled.API.dll</HintPath>
      </Reference>
      <Reference Include="Exiled.Events">
        <HintPath>..\..\..\sl_libs\Exiled.Events.dll</HintPath>
      </Reference>
      <Reference Include="HintServiceMeow">
        <HintPath>..\..\..\sl_libs\HintServiceMeow-LabAPI.dll</HintPath>
      </Reference>
      <Reference Include="LabApi">
        <HintPath>..\..\..\sl_libs\LabApi.dll</HintPath>
      </Reference>
      <Reference Include="Mirror">
        <HintPath>..\..\..\sl_libs\Mirror.dll</HintPath>
      </Reference>
      <Reference Include="Pooling">
        <HintPath>..\..\..\sl_libs\Pooling.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\..\..\sl_libs\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PhysicsModule">
        <HintPath>..\..\..\sl_libs\UnityEngine.PhysicsModule.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MySql.Data" Version="9.5.0" />
    </ItemGroup>

</Project>
